

middleData=[{
    topHeading:"INDIA'S TOUR OF WEST INDIES, 2022",
    image:"https://www.cricbuzz.com/a/img/v1/420x235/i1/c239553/jadeja-doubtful-for-wi-odis-r.jpg",
    headLine:"Jadeja doubtful for WI ODIs, Rahul unlikely for T20Is",
    headLineLink:"https://www.cricbuzz.com/cricket-news/123168/stodgy-proteas-bring-happy-memories-and-good-form-to-manchester",
    news:"While Jadeja has a knee niggle, Rahul has tested COVID-positive",
    bottomLine:"Beleaguered West Indies have their task cut out against under-powered India",
    bottomLineLine:https:"www.cricbuzz.com/cricket-news/123164/beleaguered-west-indies-have-their-task-cut-out-against-under-powered-india";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    {
    topHeading:"",
    image:"",
    headLine:"",
    headLineLink:"",
    news:"",
    bottomLine:"",
    bottomLineLine:https:"";
    }
    
    ]
leftData=[
    {
        
    }
]    